#include <gba.h>
#include <gba_sprites.h>

#include "Map.h"
#include "Engine.h"
#include "Utilities.h"
#include "Enemy_ai.h"
#include "font.h"
#include "agb.h"

#include "level_bitmaps.h"  // generated by grit
#include "char_bitmaps.h"
#include "bullet_bitmap.h"

int main(void)
{
    irqInit();
    irqEnable(IRQ_VBLANK);

    AGBPrintInit();
    // Mode 0, BG0
    REG_DISPCNT = MODE_0 | BG0_ENABLE | OBJ_ENABLE | OBJ_1D_MAP;

    // Correct BG0 setup
    REG_BG0CNT = CHAR_BASE(0) | SCREEN_BASE(31) | BG_16_COLOR | BG_SIZE_0 | BG_PRIORITY(2);
    REG_BG0HOFS = 0;

    // Load palette (4bpp = 16 colors)
	memcpy_hw(BG_PALETTE, lvl1Pal, lvl1PalLen);
	memcpy_hw(CHAR_BASE_BLOCK(0), lvl1Tiles, lvl1TilesLen);

    memcpy_hw(SPRITE_PALETTE, charPal, charPalLen);

    memcpy_hw(SPRITE_GFX,         frame_00Tiles, frame_00TilesLen);
    memcpy_hw(SPRITE_GFX + 144,   frame_01Tiles, frame_01TilesLen);
    memcpy_hw(SPRITE_GFX + 144*2, frame_02Tiles, frame_02TilesLen);
    memcpy_hw(SPRITE_GFX + 144*3, frame_03Tiles, frame_03TilesLen);
    memcpy_hw(SPRITE_GFX + 144*4, frame_04Tiles, frame_04TilesLen);
    memcpy_hw(SPRITE_GFX + 144*5, frame_05Tiles, frame_05TilesLen);
    memcpy_hw(SPRITE_GFX + 144*6, frame_06Tiles, frame_06TilesLen);
    memcpy_hw(SPRITE_GFX + 144*7, frame_07Tiles, frame_07TilesLen);
    memcpy_hw(SPRITE_GFX + 144*8, frame_08Tiles, frame_08TilesLen);
    memcpy_hw(SPRITE_GFX + 144*9, extTiles,      extTilesLen);

    memcpy_hw(SPRITE_GFX + BULLET_VRAM_ADDR, bullet1Tiles, bulletTilesLen);
    memcpy_hw(SPRITE_GFX + BULLET_VRAM_ADDR + 16, bullet2Tiles, bulletTilesLen);

    memcpy_hw(SPRITE_GFX + FONT_VRAM_ADDR, glyphTiles, glyphTilesLen);

    clear_oam();

    init_lvl(SCREEN_BASE_BLOCK(31), lvl1Map);
    reset_engine();

    while(1)
    {
        tick_before_vblank();

        VBlankIntrWait();

        tick_vblank();
    }
}
