#include <gba.h>

#include "Map.h"
#include "Engine.h"
#include "Utilities.h"
#include "Enemy_ai.h"
#include "font.h"
#include "agb.h"
#include "sound.h"
#include "monster_bitmap.h"
#include "level_data.h"  // generated by grit
#include "char_bitmaps.h"
#include "fire_bitmap.h"
#include "bullet_bitmap.h"

int main(void)
{
    irqInit();

    irqSet(IRQ_VBLANK, sound_irq);
    irqEnable(IRQ_VBLANK);

    init_sound();

    AGBPrintInit();
    // Mode 0, BG0
    REG_DISPCNT = MODE_0 | BG0_ENABLE | OBJ_ENABLE | OBJ_1D_MAP;

    // Correct BG0 setup
    REG_BG0CNT = CHAR_BASE(0) | SCREEN_BASE(31) | BG_16_COLOR | BG_SIZE_0 | BG_PRIORITY(2);
    REG_BG0HOFS = 0;

    memcpy_hw(SPRITE_PALETTE, charPal, charPalLen);

    memcpy_hw(SPRITE_GFX,         frame_00Tiles, frame_00TilesLen);
    memcpy_hw(SPRITE_GFX + 144,   frame_01Tiles, frame_01TilesLen);
    memcpy_hw(SPRITE_GFX + 144*2, frame_02Tiles, frame_02TilesLen);
    memcpy_hw(SPRITE_GFX + 144*3, frame_03Tiles, frame_03TilesLen);
    memcpy_hw(SPRITE_GFX + 144*4, frame_04Tiles, frame_04TilesLen);
    memcpy_hw(SPRITE_GFX + 144*5, frame_05Tiles, frame_05TilesLen);
    memcpy_hw(SPRITE_GFX + 144*6, frame_06Tiles, frame_06TilesLen);
    memcpy_hw(SPRITE_GFX + 144*7, frame_07Tiles, frame_07TilesLen);
    memcpy_hw(SPRITE_GFX + 144*8, frame_08Tiles, frame_08TilesLen);
    memcpy_hw(SPRITE_GFX + FRAME_J_VRAM_ADDR, frame_jTiles, frame_jTilesLen);

    memcpy_hw(SPRITE_GFX + BULLET_VRAM_ADDR, bullet1Tiles, bulletTilesLen);
    memcpy_hw(SPRITE_GFX + FIRE_VRAM_ADDR, fireTiles, fireTilesLen);
    memcpy_hw(SPRITE_GFX + ARROW_VRAM_ADDR, arrowTile, arrowTileLen);

    memcpy_hw(SPRITE_GFX + MONSTER_VRAM_ADDR,         monster_frame_0000Tiles, monster_frame_0000TilesLen);
    memcpy_hw(SPRITE_GFX + MONSTER_VRAM_ADDR + 144,   monster_frame_0001Tiles, monster_frame_0001TilesLen);
    memcpy_hw(SPRITE_GFX + MONSTER_VRAM_ADDR + 144*2, monster_frame_0002Tiles, monster_frame_0002TilesLen);
    memcpy_hw(SPRITE_GFX + MONSTER_VRAM_ADDR + 144*3, monster_frame_0003Tiles, monster_frame_0003TilesLen);
    memcpy_hw(SPRITE_GFX + MONSTER_VRAM_ADDR + 144*4, monster_frame_0004Tiles, monster_frame_0004TilesLen);
    memcpy_hw(SPRITE_GFX + MONSTER_VRAM_ADDR + 144*5, monster_frame_0005Tiles, monster_frame_0005TilesLen);
    memcpy_hw(SPRITE_GFX + MONSTER_VRAM_ADDR + 144*6, monster_frame_0006Tiles, monster_frame_0006TilesLen);
    memcpy_hw(SPRITE_GFX + MONSTER_VRAM_ADDR + 144*7, monster_frame_0007Tiles, monster_frame_0007TilesLen);
    memcpy_hw(SPRITE_GFX + MONSTER_VRAM_ADDR + 144*8, monster_frame_0008Tiles, monster_frame_0008TilesLen);
    memcpy_hw(SPRITE_GFX + MONSTER_VRAM_ADDR + 144*9, monster_frame_0009Tiles, monster_frame_0009TilesLen);

    memcpy_hw(SPRITE_GFX + BAT_VRAM_ADDR, batTiles, batTilesLen);

    black_screen();
    reset_engine(0);
    copy_shadow_oam_dma();
    while(1)
    {
        tick();

        VBlankIntrWait();

        copy_shadow_oam_dma();
    }
}
